Updating repo to match changes in ProjectX
American-Capstones/TAMU-Fall-2021 pull request #13
Opened 2021-10-01 18:40 UTC by dre8597

Co-authored-by: Austin Slobodnik <austinslobodnik@gmail.com>

### Pre-Requisites

- [X] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [X] Yes, I included and/or modified tests to cover relevant code **OR** my change is non-technical
- [X] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

### Description of Changes

Updating project to match changes added in ProjectX repo

### Related Issues

2021-10-01 19:34 UTC, johnkahn requested changes

2021-10-01 19:34 UTC, johnkahn commented on .github/labeler.yaml
> +  - packages/api/src/entities/**/*
Can you rename this file to `labeler.yml`? Found out that's why the labeler isn't running in the UTD PRs

2021-10-01 19:34 UTC, johnkahn commented on packages/api/.env.sample
> +DATABASE_URL="postgresql://localhost:5432/project-x"
```suggestion
DATABASE_URL="postgresql://localhost:5432/tamu-fall-21"
```

2021-10-03 05:43 UTC, Tabansi99 approved these changes

2021-10-03 13:03 UTC, MKanarr approved these changes
Approved.  Necessary changes to proceed with project and to proceed with issue #9

2021-10-03 13:40 UTC, sabrinalu1 approved these changes

2021-10-03 17:06 UTC, abrahamsama approved these changes

2021-10-04 15:21 UTC, johnkahn approved these changes

2021-10-04 15:21 UTC, merged